# Generated by Django 3.2.12 on 2022-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startup", "0003_alter_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(default="YHXLPOZZTO", max_length=10),
        ),
    ]
