# Generated by Django 2.2 on 2022-02-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startup", "0008_alter_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastip",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(default="NMTD9RIC5B", max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stepproduct",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
