# Generated by Django 2.2 on 2022-02-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startup", "0009_auto_20220228_1926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(default="VI4H0P4UJF", max_length=10),
        ),
    ]
