# Generated by Django 2.2 on 2022-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startup", "0012_auto_20220228_1942"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(default="ONCKXLZZXA", max_length=10),
        ),
    ]
