# Generated by Django 3.2.12 on 2022-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startup", "0015_alter_product_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="transactionid",
            field=models.TextField(default=""),
        ),
    ]
